using System.Text.Json.Serialization;

namespace FinancialTwin.API.Models
{
    public class Simulation
    {
        public Guid Id { get; set; } = Guid.NewGuid();
        public string Title { get; set; } = string.Empty; // e.g., "Master's Degree vs Index Funds"
        
        // The narrative generated by the AI:
        public string? AiGeneratedStory { get; set; } 
        
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        // Foreign Key to our User:
        public Guid UserId { get; set; }

        public decimal InitialSavings { get; set; }
        public decimal MonthlyContribution { get; set; }
        public decimal AnnualReturnRate { get; set; }
        
        public decimal AnnualVolatility { get; set; } = 0.15m;
        
        // EF Core mapping for Array (Supported seamlessly by Npgsql mapping)
        public List<decimal> P10Trajectory { get; set; } = new();
        public List<decimal> P50Trajectory { get; set; } = new();
        public List<decimal> P90Trajectory { get; set; } = new();
        
        [JsonIgnore] // Don't try to send the whole User back when fetching a simulation
        public User? User { get; set; }
    }
}
